name:  "release"

on:
    push:
        branch: "master"

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout
            - name: node
              uses: actions/setup-node
              with:
                  node-version: 12
            - name: tsc
              uses: icrawl/action-tsc@v1
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}